version: "2"

services:
  proxy:
    container_name: proxy
    command: ["echo", "'Certificates generated, exiting...'"]
    build:
      context: ./images/proxy
    image: publik-proxy
    tty: true
    links:
      - debian:components
      - debian:rabbitmq
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data/ssl:/etc/nginx/ssl
      - ./data/letsencrypt:/etc/letsencrypt
      - /etc/hosts:/etc/hosts
      - ./data/sites:/tmp/sites
    env_file:
      - .env

  debian:
    container_name: fake_components
    image: debian:buster
    command: sleep 3600
