version: "2.1"

services:
  proxy:
    container_name: proxy
    build:
      context: ./images/proxy
    image: publik-proxy
    tty: true
    ports:
      - "${HTTP_PORT:-80}:80"
      - "${HTTPS_PORT:-443}:443"
    volumes:
      - ./data/ssl:/etc/nginx/ssl
      - ./data/letsencrypt:/etc/letsencrypt
      - ./data/hosts:/etc/hosts
      - ./data/sites:/tmp/sites
    links:
      - components:components
      - rabbitmq:rabbitmq
    env_file:
      - .env
  
  components:
    container_name: components
    build:
      context: ./images/components
    image: publik-components
    command: /bin/bash
    volumes:
      - authentic2data:/var/lib/authentic2-multitenant/tenants
      - combodata:/var/lib/combo/tenants
      - fargodata:/var/lib/fargo/tenants
      - hobodata:/var/lib/hobo/tenants
      - passerelledata:/var/lib/passerelle/tenants
      - wcsdata:/var/lib/wcs
      - ./data/hosts:/etc/hosts
      - ./data/sites:/tmp/sites
      - ./data/backups:/tmp/backups
      - ./themes:/usr/share/publik/themes
    links:
      - rabbitmq:rabbitmq
    depends_on: 
      - rabbitmq
    tty: true
    env_file:
      - .env

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    mem_limit: 256M
    hostname: rabbitmq
    ports:
      - "${RABBITMQ_PORT:-5672}:5672"
      - "${RABBITMQ_MANAGEMENT_PORT:-15672}:15672"
    env_file:
      - .env

volumes:
  authentic2data:
  combodata:
  fargodata:
  hobodata:
  passerelledata:
  wcsdata:
