# To be used with docker-compose.yml
# docker-compose -f docker-compose.yml -f docker-compose.dev.yml xxx

version: "2.1"

services:
  proxy:
    links:
      - components:components
      - rabbitmq:rabbitmq
      - pgadmin:pgadmin
      - mailcatcher:webmail

  components:
    links:
      - db:db
      - rabbitmq:rabbitmq
      - mailcatcher:webmail
    depends_on: 
      - db
      - rabbitmq

  db:
    container_name: db
    build:
      context: ./images/postgresql
    image: publik-pgsql
    ports:
      - "${DB_PORT:-5432}:5432"
    env_file:
      - .env
    environment:
      - "POSTGRES_USER=$DB_ADMIN_USER"
      - "POSTGRES_PASSWORD=$PASS_POSTGRES"
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./postgresql/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d

  pgadmin:
    container_name: pgadmin
    image: chorss/docker-pgadmin4
    links:
      - db:db
    ports:
      - "${PGADMIN_PORT:-5050}:5050"
    environment:
      - "PGADMIN_SETUP_EMAIL=$ADMIN_MAIL_ADDR"
      - "PGADMIN_SETUP_PASSWORD=$PASS_POSTGRES"

  mailcatcher:
    container_name: mailcatcher
    image: ascendhit/mailcatcher
    ports:
      - "${SMTP_PORT:-1025}:1025"
      - "${MAILCATCHER_HTTP_PORT:-1080}:1080"

volumes:
  dbdata:
