# To be used with docker-compose.yml
# docker-compose -f docker-compose.yml -f docker-compose.db.yml xxx

version: "2.1"

services:
  proxy:
    links:
      - components:components
      - rabbitmq:rabbitmq
      - pgadmin:pgadmin

  components:
    links:
      - db:db
      - rabbitmq:rabbitmq
    depends_on: 
      - db
      - rabbitmq

  db:
    container_name: db
    build:
      context: ./postgresql
    image: publik-pgsql
    ports:
      - "${DB_PORT:-5432}:5432"
    env_file:
      - .env
      - ./data/config.env
      - ./data/secret.env
    environment:
      - "POSTGRES_USER=$DB_ADMIN_USER"
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./postgresql/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d

  pgadmin:
    container_name: pgadmin
    image: chorss/docker-pgadmin4
    links:
      - db:db
    ports:
      - "${PGADMIN_PORT:-5050}:5050"

volumes:
  dbdata:
