version: "2.1"

services:
  proxy:
    container_name: proxy
    build:
      context: ./images/proxy
    image: publik-proxy
    tty: true
    ports:
      - "${HTTP_PORT:-80}:80"
      - "${HTTPS_PORT:-443}:443"
    volumes:
      - ./data/ssl:/etc/nginx/ssl
      - ./data/letsencrypt:/etc/letsencrypt
      - ./data/hosts:/etc/hosts
      - ./data/sites:/tmp/sites
    links:
      - components:components
      - rabbitmq:rabbitmq
    env_file:
      - .env
  
  components:
    container_name: components
    build:
      context: ./images/components
      args:
        - authentic_version=$AUTHENTIC_VERSION
        - combo_version=$COMBO_VERSION
        - fargo_version=$FARGO_VERSION
        - hobo_version=$HOBO_VERSION
        - hobo_agent_version=$HOBO_AGENT_VERSION
        - passerelle_version=$PASSERELLE_VERSION
        - wcs_version=$WCS_VERSION
        - wcs_au_quotidien_version=$WCS_AU_QUOTIDIEN_VERSION
        - publik_common_version=$PUBLIK_COMMON_VERSION
    image: publik-components
    command: /bin/bash
    volumes:
      - authentic2data:/var/lib/authentic2-multitenant/tenants
      - combodata:/var/lib/combo/tenants
      - fargodata:/var/lib/fargo/tenants
      - hobodata:/var/lib/hobo/tenants
      - passerelledata:/var/lib/passerelle/tenants
      - wcsdata:/var/lib/wcs
      - ./data/hosts:/etc/hosts
      - ./data/sites:/tmp/sites
      - ./data/backups/last:/tmp/backup
      - ./data/themes:/tmp/themes
    links:
      - rabbitmq:rabbitmq
    depends_on: 
      - rabbitmq
    tty: true
    env_file:
      - .env

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    mem_limit: 512M
    hostname: rabbitmq
    ports:
      - "${RABBITMQ_PORT:-5672}:5672"
      - "${RABBITMQ_MANAGEMENT_PORT:-15672}:15672"
    env_file:
      - .env
    environment:
      - "RABBITMQ_DEFAULT_USER=$RABBITMQ_USER"
      - "RABBITMQ_DEFAULT_PASS=$PASS_RABBITMQ"

volumes:
  authentic2data:
  combodata:
  fargodata:
  hobodata:
  passerelledata:
  wcsdata:
